[package]
name = "andrea/repo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
signal = "sleitnick/signal@^1"
TableUtil = "sleitnick/table-util@^1"
fusion = "acecateer/fusion@0.3.1"
trove = "cody-nelson/trove@0.0.1"

# Dev
# iris = "xswezan/iris@2.0.5"
conch = "alicesaidhi/conch@0.2.3"
conch_ui = "alicesaidhi/conch-ui@0.2.3"
ingameexplorer = "brinkokevin/ingameexplorer@3.0.2"

# Melee
shapecasthitbox = "teamswordphin/shapecasthitbox@0.1.7"

# Network
BridgeNet2 = "ffrostflame/bridgenet2@^0.5"

# Voxel destruction
greedymeshing = "royal0959/rblx-nonvoxel-greedy-meshing@1.0.3"
partcache = "andremhpra/partcache@1.0.0"

# Spring
spring = "nightcycle/spring@1.0.0"

# Datastore
suphisdatastoremodule = "skylord-103/suphisdatastoremodule@1.0.0"
btreesv5 = "onv-il/btreesv5@5.0.18"